[package]
name = "msvisor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "*"
anyhow = "*"
nix = "*"
ms_hostcall = { path = "../ms_hostcall" }
log = "*"
env_logger = "*"
