[package]
name = "ms_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]

[dependencies]
# nix = "*"
once_cell = "*"
ms_hostcall = { path = "../../ms_hostcall" }
